[package]
distribution = "2201.0.0"
org = "ballerinax"
name = "peoplehr"
version = "1.1.0"
authors = ["Ballerina"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-peoplehr"
keywords = ["Human Resources/HRMS", "Cost/Paid"]
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
